### ISSUE TITLE
User should be responsible for the fragments!

### ISSUE THREAD

**Issue by IkarusInDaHouse** [LedgerHQ/recover-whitepaper#4]
Hello,
Why not adding the option that the user can store the three fragments by her/himself on a trusted location. The user is than in control of the three fragments instead of trusting an “untrusted” third party!
In that case the user has the option to recover the keys/seed phrase at any time.

**Comment by YBadiss** [comment]
Hi @IkarusInDaHouse !

Creating a solution that securely handles the seed fragments is part of the value proposition of Ledger Recover, and we expect this to be useful for most non-technical users.

You are right however that being able to leverage the security of Ledger Recover on your Nano, while not relying on a third party for storage has a strong appeal.

**This is why we wrote [this step-by-step guide](https://github.com/LedgerHQ/blue-loader-python/blob/master/ledgerblue/HowToRecover.md) on using Ledger Recover features by yourself, encrypting your seed fragments with your personal GPG key.**

We have also [open sourced](https://github.com/LedgerHQ/ledger-secure-os) the part of the firmware that handles the splitting of the shares and their encryption on the device.

Hope that helps, and if you try the "How To Recover" guide, don't hesitate to share your feedback!
